server:
  port: 8080
  servlet:
    context-path: /community
spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: 18192645021@163.com
    password: lym596..
    host: smtp.163.com
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lemon.community.bean
  configuration:
    use-generated-keys: true
#    map-underscore-to-camel-case: true
community:
  path:
    domain: http://localhost:8080
#thymeleaf:
#    prefix: classpath:/templates/  #prefix：指定模板所在的目录
#    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#    suffix: .html
#    #encoding: UTF-8
#    #content-type: text/html
#    mode: HTML5
